### ISSUE TITLE
Jenkins plugin: errant forward-slash in download path breaks downloadProgetPackage

### ISSUE THREAD

**Issue by mcascone** [Inedo/inedo-docs#115]
Please let me know if I'm doing something wrong. The `uploadProgetPackage` Jenkins command works like a charm. When trying to download, there seems to be an extra forward-slash at the start of the download path, which of course breaks the download. 

my command:
```jenkinsfile
       downloadProgetPackage downloadFolder: "${WORKSPACE}/${deployLocation}", 
                              downloadFormat: 'zip',
                              feedName: 'PlatDev',
                              groupName: "Relativity/${env.appName}/${BRANCH_NAME}",
                              packageName: "${env.appName}",
                              version: 'Latest'
```
`${WORKSPACE}` == `pwd()` == `D:\workspace\_5649-PS-jenkins-deploy-pipeline`
`${deployLocation}` == 'deploy'

Result:
```
[ProGet] Download package to /D:\workspace\_5649-PS-jenkins-deploy-pipeline/deploy
```

Note the `/` at the start of the string. So the download goes nowhere, and i can't unzip the nonexistent file. 

```
        unzip zipFile: "${deployLocation}\\*.zip"


java.io.IOException: D:\workspace\_5649-PS-jenkins-deploy-pipeline\deploy\*.zip does not exist.
```

I also tried just `.\\${deployLocation}` with the same result.

Does this only work on Linux agent/nodes? Am I doing something wrong?

thanks
max

**Comment by mcascone** [comment]
I am currently working around it by using the raw url download:
```
httpRequest outputFile: "${deployLocation}/${appName}.zip", 
                    responseHandle: 'NONE', 
                    url: 'http://proget.consilio.com/upack/PlatDev/download/Relativity/ProcessingSync/PLATDEV-5649-PS-jenkins-deploy-pipeline/ProcessingSync?latest&contentOnly=zip'
```

**Comment by apxltd** [comment]
https://forums.inedo.com/post/9916
