### ISSUE TITLE
Clarify "seamless" Inline Variable Replacement in PowerShell

### ISSUE THREAD

**Issue by apapadimoulis** [Inedo/inedo-docs#12]
https://github.com/Inedo/inedo-docs/blob/master/ExecutionEngine/components/powershell-and-shell.htm

There are several cases where we need to work-around this by doing something like

>>
   $MyPSVar = $MyOtterSCriptVar
   echo "hello $MYPsVar"
<<

**Comment by gdivis** [comment]
I know I've seen an example of this recently, but I can't remember where, and I can't seem to get this to be required in any of my testing. Is there a case you can link to of this work-around being needed? After a code inspection I don't see any cases where this would be necessary.
