### ISSUE TITLE
docker 18.09 pull image error

### ISSUE THREAD

**Issue by PhoenixChen2016** [Inedo/inedo-docs#19]
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

pull proget private registry image error
Error response from daemon: Get https://xxx/v2/: EOF

but docker version 18.06 work

**Comment by jrasch** [comment]
This repository is not monitored for support purposes, please use the QA forums: https://inedo.com/support/questions
