### ISSUE TITLE
PowerShell publishing does not use "api" user

### ISSUE THREAD

**Issue by terrabitz** [Inedo/inedo-docs#20]
According to the current PowerShell feed documentation (https://inedo.com/support/documentation/proget/feeds/powershell), the appropriate way to use a feed API key to publish modules looks like the following:

```powershell
Publish-Module -Path <ModuleFile> -NuGetApiKey api:<API Key> -Repository MyProGetFeed
```

This appears to be incorrect. After many times of attempting this method, I ran the same command without the `api:` appended to the the `NuGetApiKey`, and it appeared to work just fine:

```powershell
Publish-Module -Path <ModuleFile> -NuGetApiKey <API Key> -Repository MyProGetFeed
```

**Comment by gdivis** [comment]
Thanks! You're right - "api:" shouldn't be there when supplying the API key directly.
