### ISSUE TITLE
There was an error with a connector: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by xyz0822** [Inedo/inedo-docs#202]
error when connect to nuget :There was an error with a connector: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel
os:windows server 2008 r2 sp1
proget-version:5.2.31
nuget-url:https://api.nuget.org/v3/index.json

**Comment by apxltd** [comment]
Please use http://forums.inedo.com/ for communicating project issues; this is only for our documentation

https://inedo.com/support/kb/1161/tls-v12-configuration-and-connection-errors
