### ISSUE TITLE
Publish scoped npm packages

### ISSUE THREAD

**Issue by TheHunter** [Inedo/inedo-docs#3]
Hi all,
I tried to publish my scoped package using npm command line, but I have this error:

npm ERR! path C:\Users\[**my_local_dir**]\AppData\Local\Temp\npm-11196-567fef20\tmp\fromDir-cf070584\package.tgz

the package name is **@myscope/cache,** and the commandline is:
**npm publish --registry=[my_npm_repo] --scope=myscope --access=public**

Previously I've done the login to my registry, and authentication seems OK.

Making the same instruction on npm.org (using my credentials npm credentials) works perfectly.

Anyone could tell me if I was wrong ?

Thanks in advance.

**Comment by TheHunter** [comment]
Can anyone respond to this issue?
My company uses Proget, but if this a unsolvable problem We could adopt another solution like MYGet or other.

**Comment by apapadimoulis** [comment]
This github project was mistakenly open for issues, so please submit Q&A to http://inedo.com/support/questions

The error message doesn’t appear to say anything, and it’s not even clear if the request is going to ProGet, or if your npm client is misconfigured.

I would recommend to “Delete everything” (i.e. your local npm configuration), and try fresh.  You can also search for that particular format of error, and see what other npm users said.

If you do find it has something to do with ProGet (as opposed to local configuration), you can submit it to the Q&A site linked above --- but when you submit it to the above, please make sure to find parts of the logs, or message that give some sort of indication what the error is. Note that you can also go to Admin > Erorr logs and see errors logged to the server.
