### ISSUE TITLE
How to make a request to an API? Documentation is not clear

### ISSUE THREAD

**Issue by brunomartinspro** [Inedo/inedo-docs#49]
The usage of api endpoints are not clear, concrete examples of how to make a request is required.

**Example:** 
How do i make a request with an APIKey to the endpoint Feeds_CreateFeed of the Native API?
The link [https://inedo.com/support/documentation/proget/reference/api/native](https://inedo.com/support/documentation/proget/reference/api/native) does not specify.

Tried passing the key as specified in [https://github.com/Inedo/inedo-docs/blob/master/ProGet/administration/security/api-keys.md](https://github.com/Inedo/inedo-docs/blob/master/ProGet/administration/security/api-keys.md) but no success.

**Comment by brunomartinspro** [comment]
First Request:

http://feeds.fd.local:2000/api/Feeds_CreateFeed

User-Agent: Fiddler
apiKey: lmwqlXscnXPRsIulnssx

{
     "Feed_Name"  : "PaymentGateway-FeedApiTest", 
     "FeedType_Name"  : "nuget"
}

Response: Not Found

Tried replicating the request that the UI uses with an api key but with no success:

![02](https://user-images.githubusercontent.com/7645736/56043661-9e2e6000-5d35-11e9-80f7-8067a9721723.PNG)
![01](https://user-images.githubusercontent.com/7645736/56043662-9e2e6000-5d35-11e9-9ef6-de34a0f8865b.PNG)

**Comment by brunomartinspro** [comment]
After trial and error and reading other questions i found an url example.
Turns out the request worked with:

**URL:** 
http://feeds.fd.local:2000/api/json/Feeds_CreateFeed

**Header:** 
Content-Type: application/json

**Body:**
{
     "Feed_Name"  : "PaymentGateway-FeedApiTest231231231", 
     "FeedType_Name"  : "nuget",
	   "API_Key" : "lmwqlXscnXPRsIulnssx"
}

This really needs to be documented.

**Comment by jrasch** [comment]
As of ProGet 5.2 (in beta now, to be released end of next week) we have added a specialized API for feed creation and management. The documentation for it is in a branch currently but will be merged before release: https://github.com/Inedo/inedo-docs/blob/proget-5.2/ProGet/reference/api/feed-management.md

This endpoint will still need one more update (specifically changes to `syncToken` and `replicationMode` to account for the changes to feed replication: https://inedo.myjetbrains.com/youtrack/issue/PG-1478
