### ISSUE TITLE
ProGet offline installation. 

### ISSUE THREAD

**Issue by bateskevin** [Inedo/inedo-docs#5]
Hi!

I was just wondering why ProGet needs an internetconnection for the licencefree installation. If I want to install the free version if ProGet on a machine without internet connection The Free forever and the basic licence are greyed out, leaving me with the option to enter an enterprise licence. 

Hope this is not the wrong spot to mention this. 

Cheers!

Kevin

**Comment by apapadimoulis** [comment]
The support forums are really the best way, but I can give a quick answer. Just request a license key manually, from the myInedo portal. Then you can enter it in the installer. The installer can't access, which is why it's grayed
________________________________
