### ISSUE TITLE
Virtual package format documentation seems to contradict itself

### ISSUE THREAD

**Issue by wldevries** [Inedo/inedo-docs#7]
> A virtual package is just like a regular package, except without any actual content (i.e. your application files and components). It can contain all of the same metadata that a regular package has, but the contents themselves are external to the package file.

On the _What is a Virtual Package?_ page it is described that a virtual package is a zip file just like a normal univesal package.

> There's not much to virtual package; it's just a JSON-based text file with a .vpack file extension.

On the _Virtual Package Format_ page it seems to imply that the package is just a single json file with a vpack extension.

I've tried both. When I push the virtual package as a standard json file with a .vpack extension I get the following error message:

> The specified file is not a valid universal package: End of Central Directory record could not be found.

When I push the virtual package as a zipped `upack.json` file inside a `.vpack` file proget receives it just fine, but when I install it using upack.exe it does not seem to recognize that it is a virtual package, no files or directories are extracted.

The contents of the virtual package json is listed below. The referenced packages install just fine by themselves.
```
{
    "group": "AloisDance",
    "name": "Rozenwals",
    "version": "1.0.0",
    "contents": [ "AloisDance/Rozenwals.media:1.0.0", "AloisDance/Rozenwals.meta:1.0.0" ]
}
```

**Comment by apapadimoulis** [comment]
Thanks for the feedback; unless you're using an older version of ProGet (vpack was added in 5.1), this should be supported. Otherwise, it sounds like a bug.

Consuming the package is just like a regular package, but the package itself is really just a .json file with a special .vpack extension.  We will try to clarify this in the next update!
