### ISSUE TITLE
proget部署时添加端口号下载包失败

### ISSUE THREAD

**Issue by yexianzhu** [Inedo/inedo-docs#71]
如题，在服务器中部署了proget，地址为：ip:port/nuget，将该包源设置到vs2019中，在包列表可以看到自定义nuget包，点击安装时，nuget管理器发现下载包时，会自动将port丢弃，直接以ip/nuget获取包，导致返回401错误。
在官方文档中，未找到相关配置项。敬请告知！

**Comment by jrasch** [comment]
This is a repository designed for the Inedo documentation on inedo.com. For community product support, visit the [support forums](https://forums.inedo.com), or if you are an enterprise user, visit the [submit ticket](https://inedo.com/support/submit-ticket) page.
