### ISSUE TITLE
Extensions in ProGet v4, how to have ProGet loaded the zipped .progetx file?

### ISSUE THREAD

**Issue by stryt2** [Inedo/inedo-docs#8]
In the documentation page for "[Extending ProGet](https://inedo.com/support/documentation/proget/administration/extensions)", 
> To deploy the extension to ProGet v4, add the compiled extension .dll to a zip file of the same name, with the extension .progetx. Note that the .progetx file must have the same file name as the primary assembly it contains; for example, MyExtension.progetx must contain MyExtension.dll.
> 
> You can verify that your extension has loaded correctly by viewing the Extensions Overview page from within the ProGet v4 Administration section. From there you will see all of the extensions that are loaded in ProGet v4 and the services they provide.

This lacks the information as how and where to upload the `MyExtension.progetx`. Cannot find more information/examples either. If following the procedure describes in the "[Hosting a Private Extensions Feed](https://inedo.com/support/documentation/inedosdk/hosting)", ProGet then got unhappy about the format not being an Universal Package Format. I felt very lost with the documentations on how to create and upload a custom extension. 

Moreover, does the `MyExtension.progetx` **only** need to include `MyExtension.dll` or does it need other files created after built with MSVS (e.g. `ProGetCore.dll`, `InedoLib.dll`)? What about `upack.json`?

Thank you for your help. 

ProGet Version: 4.7.14 (Build 4)

**Comment by jrasch** [comment]
To host your own gallery, you need ProGet v5, but that is a separate feature altogether, as are the Universal Package formatted extensions in v5.

If all you are doing is creating a custom extension, then to add it to ProGet v4, follow these steps:

1. Zip the build output into `MyExtension.progetx` (i.e. only include `MyExtension.dll`, unless you have other DLLs you want included, and note that all of the SDK extensions (InedoLib, ProGetCore, etc), should *not* be included in the zip file, in VS just set `Copy Local` to `false` and `Specific Version` to `false` in the project references)
2. The zip file name needs to match the DLL name exactly
3. Ensure the `Extensions.Path` configuration setting in the software is set to a value, and note it (or set one and note it)
4. Copy the file into the ProGet extensions directory on disk at the path in step 3
5. Restart the web site (service or app pool) and ProGet service

**Comment by stryt2** [comment]
So the only way "upload" an custom extension to ProGet v4 is copying the `MyExtension.progetx` to the ProGet extensions directory on disk?

**Comment by jrasch** [comment]
Oh, I thought you meant you wanted to consume the extension within ProGet. To host a feed for extensions (i.e. a source for *other* products to pull them from) you must use the Universal Package format (i.e. `.upack`), and to consume them (i.e. change the feed URL in each product) you would need BuildMaster v6, Otter v2, and ProGet v5.

**Comment by stryt2** [comment]
My apology, sorry for my confusing word choices. 

Essentially, what I am trying to do is to create an extension for ProGet v4 that can override the existing "License Rules" that has been set in ProGet. 

At the moment, I have created a testing local ProGet server on `localhost:xx` so that if I put the `MyExtension.progetx` in the extension path on local disk (e.g. `C:\ProgramData\ProGet\Extensions`), `MyExtension` is picked up from the server. 

But for the real server, even though I know where the path on local disk is (from looking up the setting in "Advanced Settings" page), I do not have access to the local disk (i.e. it is on an unknown different machine).

So I was asking if the only way to install `MyExtension` is to find out where this "unknown different machine" is and put the `MyExtension.progetx` to its local disk or there is a way I can somehow upload this `MyExtension.progetx` to the server that is hosted on the "unknown different machine"?

Hope this makes my question clearer. Again, thank you for all the help.

**Comment by jrasch** [comment]
No worries, but unfortunately there is no other way to load one in ProGet v4 besides putting the file in the extensions path. It wouldn't be a bad idea to have an "upload extension" page, but since v5 already supports custom feeds for extensions it lessens the value of that as a new feature.

As a workaround, could you change the extensions path to a share drive or UNC path, e.g. `\\file-server-you-can-access\c$\Extensions`, and then put the extensions in there from your machine?

**Comment by stryt2** [comment]
Yes, I would be able to do that. Closing the issue now. Thanks.
