### ISSUE TITLE
Link to OSS Index integration is broken

### ISSUE THREAD

**Issue by Vaccano** [Inedo/inedo-docs#83]
This page https://docs.inedo.com/docs/proget/compliance/vulnerabilities has the following text:

       See Integrating ProGet with OSS Index

That links to this document:

https://docs.inedo.com/docs/proget/compliance/vulnerabilities/vor

That link goes to a page that shows this error:

A content file at C:\Websites\InedoDocs\HtmlContent\WebContent\#404.htm could not be loaded.

I would like to read how to integrate in the OSS Index....

**Comment by apxltd** [comment]
seems fixed a while ago, thanks for reporting :)
